/*
-- Query: SELECT * FROM bquizgame.answer
-- Date: 2020-03-05 20:33
*/
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (1,'złożonych',1,1);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (2,'prostych',0,1);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (3,'promieniotwórczych',0,1);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (4,'fosforyzujących',0,1);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (5,'4',1,2);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (6,'6',0,2);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (7,'2',0,2);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (8,'8',0,2);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (9,'łysnia',1,3);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (10,'melonik',0,3);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (11,'laseczka',0,3);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (12,'wąsik',0,3);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (13,'mianownik',1,4);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (14,'biernik',0,4);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (15,'wołacz',0,4);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (16,'celownik',0,4);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (17,'zmienia kolor na czerwony',1,5);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (18,'zmienia kolor na zielony',0,5);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (19,'zmienia kolor na żółty',0,5);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (20,'trwale się odbarwia',0,5);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (21,'Woda',1,6);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (22,'Chloroform',0,6);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (23,'Benzen',0,6);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (24,'Ksylen',0,6);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (25,'tlenku węgla (CO) i wodoru (H2)',1,7);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (26,'tlenu (O2) i wodoru (H2)',0,7);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (27,'metanu (CH4) i wody (H2O)',0,7);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (28,'dwutlenku węgla (CO2) i wodoru (H2)',0,7);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (29,'cząstkom złota',1,8);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (30,'związkom manganu',0,8);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (31,'związkom kobaltu',0,8);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (32,'cząstkom chromu',0,8);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (33,'zasadą',1,9);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (34,'kwasem',0,9);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (35,'izotopem',0,9);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (36,'mieszaniną',0,9);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (37,'Fermentacja wina',1,10);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (38,'Słodzenie herbaty',0,10);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (39,'Wybuch bomby wodorowej',0,10);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (40,'Topienie się śniegu',0,10);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (41,'topnieniu',1,11);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (42,'polimeryzacji',0,11);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (43,'rozpuszczaniu',0,11);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (44,'sublimacji',0,11);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (45,'fosforu',1,12);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (46,'chloru',0,12);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (47,'potasu',0,12);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (48,'polonu',0,12);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (49,'żelaza',1,13);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (50,'azotu',0,13);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (51,'krzemu',0,13);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (52,'potasu',0,13);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (53,'srebrzysty metal',1,14);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (55,'gęsta, brązowa ciecz',0,14);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (56,'kobalt nie występuje w temperaturze pokojowej',0,14);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (54,'zielonkawy gaz',0,14);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (57,'chlorku sodu',1,15);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (58,'chlorku potasu',0,15);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (59,'chloranu amonu',0,15);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (60,'bezwodnika potasowego',0,15);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (61,'żółto',1,16);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (62,'zielono',0,16);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (63,'czerwono',0,16);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (64,'niebiesko',0,16);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (65,'wiązanie kowalencyjne',1,17);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (66,'wiązanie wodorowe',0,17);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (67,'wiązanie peptydowe',0,17);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (68,'wiązanie van der Waalsa',0,17);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (69,'liczby atomowej',1,18);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (70,'liczby masowej',0,18);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (71,'daty odkrycia',0,18);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (72,'stanu skupienia',0,18);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (73,'Au',1,19);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (74,'Ag',0,19);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (75,'Cu',0,19);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (76,'Ca',0,19);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (77,'Hg',1,20);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (78,'Ag',0,20);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (79,'Pb',0,20);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (80,'Rt',0,20);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (81,'tlenek węgla',1,21);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (82,'dwutlenek węgla',0,21);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (83,'metan',0,21);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (84,'dwutlenek chromu',0,21);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (85,'węgiel',1,22);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (86,'chrom',0,22);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (87,'chlor',0,22);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (88,'cynk',0,22);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (89,'Sacharoza',1,23);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (90,'Laktoza',0,23);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (91,'Mimoza',0,23);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (92,'Doskoza',0,23);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (93,'Chlorkiem sodu',1,24);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (94,'Chlorkiem glinu',0,24);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (95,'Chlorkiem wapnia',0,24);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (96,'Chlorkiem srebra',0,24);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (97,'Alkoholowej',1,25);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (98,'Masłowej',0,25);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (99,'Octowej',0,25);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (100,'Mlekowej',0,25);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (101,'Jest substancją silnie żrącą',1,26);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (102,'Stanowi 60-70% masy człowieka',0,26);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (103,'Jest powszechnym środkiem gaśniczym',0,26);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (104,'Ma budowę polarną',0,26);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (105,'Nie rozpuszcza tłuszczy',1,27);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (106,'Łatwo miesza się z wodą',0,27);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (107,'Jest używana w produkcji kosmetyków',0,27);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (108,'Jest używana w produkcji materiałów wybuchowych',0,27);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (109,'Emulgatory',1,28);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (110,'Żele',0,28);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (111,'Zole',0,28);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (112,'Liozole',0,28);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (113,'Gaśnica',1,29);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (114,'Reflektor',0,29);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (115,'Żelazko parowe',0,29);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (116,'Maszyna dymna',0,29);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (117,'Kiszeniem',1,30);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (118,'Flambirowaniem',0,30);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (119,'Liofilizacją',0,30);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (120,'Marynowaniem',0,30);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (121,'Jest substancją nieszkodliwą dla ludzkiego organizmu',1,31);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (122,'Spala się bladoniebieskim płomieniem',0,31);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (123,'W czystej postaci jest bezbarwną cieczą',0,31);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (124,'Miesza się z wodą w każdej proporcji',0,31);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (125,'Aspiryny',1,32);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (126,'Wazeliny',0,32);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (127,'Atramentu',0,32);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (128,'Żelatyny',0,32);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (129,'Parafiny',1,33);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (130,'Bakelitu',0,33);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (131,'Silikonu',0,33);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (132,'Epidianu',0,33);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (133,'1772',1,34);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (134,'1727',0,34);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (135,'1777',0,34);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (136,'1791',0,34);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (137,'1999',1,35);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (138,'1990',0,35);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (139,'1997',0,35);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (140,'2000',0,35);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (141,'1 maja 2004',1,36);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (142,'1 stycznia 2000',0,36);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (143,'1 lipca 2005',0,36);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (144,'11 listopada 2005',0,36);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (145,'Dywizjon 303',1,37);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (146,'Dywizjon 300',0,37);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (147,'Dywizjon 301',0,37);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (148,'Dywizjon 302',0,37);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (149,'1797',1,38);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (150,'1781',0,38);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (151,'1805',0,38);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (152,'1776',0,38);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (153,'22 lipca 1983',1,39);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (154,'5 października 1983',0,39);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (155,'5 kwietnia 1989',0,39);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (156,'1 sierpnia 1989',0,39);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (157,'upałem',1,40);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (158,'zamiecią śnieżną',0,40);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (159,'epidemią choroby',0,40);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (160,'zgonem',0,40);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (161,'Gertruda Mieszkówna',1,41);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (162,'Wincenty Kadłubek',0,41);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (163,'Andrzej Grzymała',0,41);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (164,'Wincenty z Kielczy',0,41);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (165,'Nigdy',1,42);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (166,'w XIV wieku',0,42);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (167,'w XV wieku',0,42);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (168,'w XVI wieku',0,42);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (169,'Wielki',1,43);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (170,'Pobożny',0,43);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (171,'Stary',0,43);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (172,'nie posiadał on przydomka',0,43);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (173,'30 czyli 2 mendle',1,44);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (174,'100 jak dzisiaj',0,44);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (175,'60 czyli kopę',0,44);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (176,'12 czyli tuzin',0,44);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (177,'Mikołaj I Romanow',1,45);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (178,'Stanisław August Poniatowski',0,45);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (179,'Aleksander I Romanow',0,45);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (180,'Zygmunt II August',0,45);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (181,'10',1,46);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (182,'2',0,46);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (183,'6',0,46);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (184,'13',0,46);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (185,'wygnany król Szwecji',1,47);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (186,'syn księcia pomorskiego',0,47);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (187,'zbuntowany komtur krzyżacki',0,47);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (188,'najmłodszy brat Jagiełły',0,47);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (189,'1918',1,48);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (190,'1917',0,48);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (191,'1818',0,48);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (192,'1819',0,48);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (193,'Gniezno',1,49);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (194,'Warszawa',0,49);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (195,'Kraków',0,49);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (196,'Poznań',0,49);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (197,'W 1795 przez Rosję, Prusy i Austrię.',1,50);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (198,'W 1772 przez Rosję, Prusy i Austrię.',0,50);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (199,'W 1772 przez Prusy, Litwę i Austrię.',0,50);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (200,'W 1793 przez Prusy, Rosję.',0,50);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (201,'\"Pieśń Legionów Polskich we Włoszech\"',1,51);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (202,'\"Pieśń Dąbrowskiego\"',0,51);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (203,'\"Pieśń żołnierska\"',0,51);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (204,'\"Pieśń Legionistów Polskich\"',0,51);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (205,'autor nie jest znany',1,52);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (206,'Michał Kleofas Ogiński',0,52);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (207,'Józef Wybicki',0,52);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (208,'Fryderyk Chopin',0,52);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (209,'29.09.1747',1,53);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (210,'20.07.1743',0,53);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (211,'20.07.1745',0,53);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (212,'29.09.1750',0,53);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (213,'politykiem',1,54);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (214,'generałem',0,54);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (215,'księdzem',0,54);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (216,'artystą',0,54);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (217,'Sześć i refren',1,55);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (218,'Cztery i refren',0,55);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (219,'Pięć i refren',0,55);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (220,'Siedem i refren',0,55);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (221,'Karola X Gustawa',1,56);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (222,'Karola XI',0,56);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (223,'Krystyny Wazówny',0,56);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (224,'Gustawa II Adolfa',0,56);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (225,'Tadeusz Kościuszko',1,57);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (226,'Kazimierz Pułaski',0,57);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (227,'Stanisław Żółkiewski',0,57);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (228,'Jan III Sobieski',0,57);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (229,'\"Kiedy my żyjemy\"',1,58);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (230,'\"Póki my żyjemy\"',0,58);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (231,'\"Dopóki my żyjemy\"',0,58);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (232,'\"Jeśli my żyjemy\"',0,58);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (233,'\"Słuchaj jeno, pono nasi biją w tarabany\"',1,59);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (234,'\"Słuchaj że no, pono nasi biją w tarabany\"',0,59);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (235,'\"Słuchaj jeno, bo to nasi biją w tarabany\"',0,59);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (236,'\"Słuchaj, gdyż to nasi biją w tarabany\"',0,59);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (237,'Wisła i Warta',1,60);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (238,'Wisła i Odra',0,60);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (239,'Warta i Odra',0,60);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (240,'Odra i Bug',0,60);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (241,'w Będominie',1,61);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (242,'w Warszawie',0,61);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (243,'w Poznaniu',0,61);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (244,'w Radomiu',0,61);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (245,'1655',1,62);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (246,'1665',0,62);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (247,'1566',0,62);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (248,'1565',0,62);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (249,'1683',1,63);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (250,'1863',0,63);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (251,'1638',0,63);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (252,'1883',0,63);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (253,'19 stycznia 1945',1,64);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (254,'18 stycznia 1944',0,64);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (255,'20 stycznia 1946',0,64);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (256,'15 stycznia 1949',0,64);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (257,'1793',1,65);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (258,'1914',0,65);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (259,'1863',0,65);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (260,'1916',0,65);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (261,'beznoga jaszczurka',1,66);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (262,'żyjący w Polsce wąż',0,66);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (263,'słodkowodna mątwa',0,66);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (264,'larwa żmii',0,66);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (265,'symbiozy',1,67);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (266,'konwergencji',0,67);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (267,'apoptozy',0,67);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (268,'dystrofii',0,67);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (269,'wytwarzanie energii',1,68);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (270,'transport DNA',0,68);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (271,'ochronę przed wirusami',0,68);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (272,'utrzymanie sztywności błony komórkowej',0,68);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (273,'podobieństwo wilka workowatego i szakala złocistego',1,69);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (274,'gruczoł jadowy skorpiona',0,69);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (275,'współpraca błazenka i ukwiału',0,69);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (276,'budowa skrzydła kolibra',0,69);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (277,'utrzymanie równowagi i koordynacja ruchów',1,70);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (278,'przetwarzanie impulsów wzrokowych',0,70);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (279,'zachowywanie wspomnień długotrwałych',0,70);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (280,'wytwarzanie impulsów koordynujących działanie półkul',0,70);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (281,'adenozyna, guaranina, tryptofan',1,71);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (282,'alanina, glicyna, histydyna, seryna',0,71);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (283,'adenina, guanina, cytozyna, tymina',0,71);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (284,'DNA tworzą aminokwasy, nie zasady',0,71);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (285,'ssak',1,72);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (286,'torbacz',0,72);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (287,'waleń',0,72);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (288,'obleniec',0,72);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (289,'woda i dwutlenek węgla pod wpływem światła zamieniają się w glukozę i tlen',1,73);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (290,'tlen i węgiel zamieniane są pod wpływem światła w tlenek węgla i wodę',0,73);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (291,'tlen i węgiel zamieniane są pod wpływem światła w dwutlenek węgla i wodę',0,73);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (292,'woda i tlen absorbowane są przez bakterie symbiotyczne roślin zielonych',0,73);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (293,'wydala nadmiar wody za pomocą wodniczek tętniących',1,74);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (294,'ma liczne chloroplasty o zróżnicowanym kształcie',0,74);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (295,'porusza się za pomocą długiej wici',0,74);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (296,'ma twardą ścianę komórkową z otworem światłoczułym',0,74);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (297,'skrzelom',1,75);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (298,'tchawkom',0,75);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (299,'oskrzelom',0,75);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (300,'chłonkom',0,75);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (301,'Komórka bakterii',1,76);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (302,'Komórka zwierzęca',0,76);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (303,'Komórka roślinna',0,76);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (304,'Komórka grzyba',0,76);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (305,'Kość ciemieniowa',1,77);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (306,'Kość czołowa',0,77);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (307,'Kość klinowa',0,77);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (308,'Kość potyliczna',0,77);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (309,'Jest to skolioza.',1,78);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (310,'Jest to nadmierna kifoza.',0,78);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (311,'Jest to nadmierna lordoza.',0,78);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (312,'Plecy okrągło-wklęsłe.',0,78);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (313,'Trąbocyty (płytki krwi)',1,79);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (314,'Erytrocyty (krwinki czerwone)',0,79);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (315,'Leukocyty (krwinki białe)',0,79);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (316,'Hemoglobina (białko)',0,79);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (317,'Poprzecznie prążkowanej',1,80);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (318,'Gładkiej',0,80);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (319,'Łącznej',0,80);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (320,'Pionowo prążkowanej',0,80);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (321,'Mocznik',1,81);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (322,'Białko',0,81);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (323,'Sok trzustkowy',0,81);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (324,'Cukry',0,81);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (325,'Glukagon',1,82);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (326,'Insulina',0,82);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (327,'Tyroksyna',0,82);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (328,'Testosteron',0,82);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (329,'Płat potyliczny',1,83);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (330,'Płat czołowy',0,83);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (331,'Płat skroniowy',0,83);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (332,'Płat ciemieniowy',0,83);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (333,'W oku',1,84);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (334,'W uszach',0,84);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (335,'Na języku',0,84);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (336,'W nosie',0,84);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (337,'Zaćma',1,85);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (338,'Jaskra',0,85);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (339,'Jęczmień',0,85);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (340,'Zapalenie spojówek',0,85);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (341,'Tak, ale tylko w filmach niemieckich',1,86);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (342,'Nigdy',0,86);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (343,'Tak, ale tylko w filmach amerykańskich',0,86);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (344,'Tak, ale tylko w filmach polskich, zanim zaczęła światową karierę',0,86);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (345,'\"Pan Tadeusz\"',1,87);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (346,'Pokrewieństwo - są daleką rodziną',0,87);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (347,'Poglądy polityczne',0,87);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (348,'Wegetarianizm',0,87);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (349,'Polskiej',1,88);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (350,'Czeskiej',0,88);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (351,'Brazylijskiej',0,88);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (352,'Niemieckiej',0,88);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (353,'Jidysz',1,89);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (354,'Angielskim',0,89);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (355,'Polskim',0,89);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (356,'Rosyjskim',0,89);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (357,'\"Ziemia obiecana\"',1,90);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (358,'\"Dzięcioł\"',0,90);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (359,'\"Lekarstwo na miłość\"',0,90);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (360,'\"Podwójne życie Weroniki\"',0,90);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (361,'\"Przeminęło z wiatrem\"',1,91);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (362,'\"Obywatel Kane\"',0,91);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (363,'\"Casablanca\"',0,91);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (364,'\"Wielki Gatsby\"',0,91);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (365,'W Odessie',1,92);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (366,'W Sankt Petersburgu',0,92);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (367,'W Moskwie',0,92);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (368,'We Władywostoku',0,92);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (369,'Są to inicjały znanych aktorek (Brigitte Bardot, Claudia Cardinale, Marilyn Monroe)',1,93);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (370,'To oznaczenia różnych grup wiekowych, dla których przeznaczone są filmy',0,93);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (371,'W ten sposób komisje kolaudacyjne oceniają jakość filmu przed dopuszczeniem go na ekrany',0,93);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (372,'Są to oznaczenia rzędów w bardzo dużych salach kinowych',0,93);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (373,'Los Angeles',1,94);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (374,'Nowego Jorku',0,94);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (375,'Las Vegas',0,94);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (376,'San Francisco',0,94);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (377,'We Francji',1,95);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (378,'W Rosji',0,95);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (379,'W Stanach Zjednoczonych',0,95);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (380,'W Polsce',0,95);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (381,'\"Apollo 13\"',1,96);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (382,'\"2001: Odyseja kosmiczna\"',0,96);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (383,'\"Interstellar\"',0,96);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (384,'\"Marsjanin\"',0,96);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (385,'\"Człowiek z blizną\"',1,97);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (386,'\"Ziarno prawdy\"',0,97);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (387,'\"Kłamca, kłamca\"',0,97);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (388,'\"Ojciec chrzestny\"',0,97);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (389,'\"Titanic\"',1,98);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (390,'\"Kariera Nikosia Dyzmy\"',0,98);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (391,'\"Ostatni król Szkocji\"',0,98);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (392,'\"Slumdog\"',0,98);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (393,'\"Gwiezdne wojny\"',1,99);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (394,'\"Pod Mocnym Aniołem\"',0,99);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (395,'\"Transporter: Nowa moc\"',0,99);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (396,'\"Odyseja kosmiczna\"',0,99);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (397,'\"Czas Apokalipsy\"',1,100);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (398,'\"Psy\"',0,100);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (399,'\"Szeregowiec Ryan\"',0,100);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (400,'\"Szyfry wojny\"',0,100);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (401,'\"Casablanca\"',1,101);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (402,'\"Przeminęło z wiatrem\"',0,101);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (403,'\"Duma i uprzedzenie\"',0,101);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (404,'\"Pamiętnik\"',0,101);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (405,'\"Forrest Gump\"',1,102);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (406,'\"Charlie i fabryka czekolady\"',0,102);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (407,'\"Leon zawodowiec\"',0,102);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (408,'\"Zielona mila\"',0,102);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (409,'\"Kingsajz\"',1,103);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (410,'\"Brunet wieczorową porą\"',0,103);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (411,'\"Miś\"',0,103);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (412,'\"Nic śmiesznego\"',0,103);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (413,'\"Terminator 2\"',1,104);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (414,'\"Robocop\"',0,104);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (415,'\"Taksówkarz\"',0,104);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (416,'\"Predator\"',0,104);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (417,'\"Przeminęło z wiatrem\"',1,105);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (418,'\"Wichrowe wzgórza\"',0,105);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (419,'\"Kiedy Harry poznał Sally\"',0,105);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (420,'\"Pamiętnik\"',0,105);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (421,'\"Miś\"',1,106);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (422,'\"Brunet wieczorową porą\"',0,106);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (423,'\"Zmiennicy\"',0,106);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (424,'\"Alternatywy 4\"',0,106);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (425,'żmij',1,107);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (426,'żmiji',0,107);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (427,'żmii',0,107);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (428,'żmi',0,107);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (429,'wybuchnęła lub wybuchła, użycie zależy od kontekstu',1,108);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (430,'wybuchnęła',0,108);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (431,'wybuchła',0,108);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (432,'żadna z odpowiedzi nie jest poprawna',0,108);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (433,'z Adamem Latą',1,109);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (434,'z Adamem Lato',0,109);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (435,'z Adamem Latem',0,109);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (436,'z Adamem Latę',0,109);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (437,'rew',1,110);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (438,'rwew',0,110);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (439,'rwów',0,110);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (440,'rwy',0,110);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (441,'M. pług - D. pługa',1,111);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (442,'M. pług - D. pługu',0,111);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (443,'M. pług - B. pługi',0,111);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (444,'M. pług - B. pługu',0,111);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (445,'przysuski',1,112);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (446,'przysuchowski',0,112);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (447,'przysuchowszczyński',0,112);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (448,'przysuchański',0,112);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (449,'Wierzby iwy',1,113);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (450,'Wierzbie iwa',0,113);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (451,'Wierzby iwa',0,113);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (452,'Wierzbie iwie',0,113);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (453,'Jedlinie-Zdrój',1,114);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (454,'Jedliną-Zdrojem',0,114);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (455,'Jedlinie-Zdroju',0,114);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (456,'Jedlina-Zdrój',0,114);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (457,'taxi, kakadu, tabu, atelier',1,115);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (458,'logo, radio, kiwi, atelier',0,115);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (459,'studio, taxi, kiwi, bikini',0,115);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (460,'kamikaze, tabu, menu, lasso',0,115);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (461,'dżdżysty',1,116);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (462,'dżczysty',0,116);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (463,'dżdzysty',0,116);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (464,'dzdżysty',0,116);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (465,'wyrazy pokrewne',1,117);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (466,'synonimy',0,117);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (467,'antonimy',0,117);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (468,'homonimy',0,117);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (469,'brednie',1,118);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (470,'wyszukane słowa',0,118);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (471,'mądrości',0,118);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (472,'typ rosyjskich rękawiczek',0,118);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (473,'czasownik',1,119);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (474,'orzeczenie',0,119);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (475,'przymiotnik',0,119);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (476,'przydawka',0,119);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (477,'1999',1,120);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (478,'2000',0,120);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (479,'2010',0,120);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (480,'2001',0,120);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (481,'Lech Wałęsa',1,121);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (482,'Tadeusz Mazowiecki',0,121);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (483,'Aleksander Kwaśniewski',0,121);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (484,'Bronisław Komorowski',0,121);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (485,'na policjantów',1,122);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (486,'na kobiety lekkich obyczajów',0,122);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (487,'na osobę w okularach',0,122);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (488,'na złodzei',0,122);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (489,'motyl',1,123);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (490,'szmata do podłogi',0,123);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (491,'sklep z używanymi ubraniami',0,123);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (492,'kapelusz',0,123);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (493,'kanapka z dwóch kromek chleba',1,124);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (494,'wieko, pokrywa',0,124);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (495,'potocznie pośladki',0,124);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (496,'nóż',0,124);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (497,'dają do zjedzenia dzieciom',1,125);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (498,'dają do zjedzenia psu lub kotu',0,125);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (499,'zakładają na siebie w zimie',0,125);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (500,'przykrywają się nią w nocy',0,125);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (501,'w Poznaniu',1,126);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (502,'na Śląsku',0,126);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (503,'w Szczecinie',0,126);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (504,'w Warszawie',0,126);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (505,'tramwaj',1,127);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (506,'dzwon',0,127);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (507,'osoba leniwa',0,127);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (508,'sznurek',0,127);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (509,'zajezdnię tramwajową',1,128);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (510,'końcówkę chleba',0,128);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (511,'raport podsumowujący',0,128);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (512,'weekend',0,128);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (513,'bilet okresowy',1,129);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (514,'policyjne koguty',0,129);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (515,'lampę błyskową',0,129);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (516,'lustro',0,129);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (517,'Podlasie',1,130);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (518,'Wielkopolska',0,130);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (519,'Śląsk',0,130);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (520,'Kaszuby',0,130);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (521,'jednorazowej torbie foliowej',1,131);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (522,'ulotce',0,131);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (523,'lekkiej kurtce',0,131);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (524,'kradzieży',0,131);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (525,'opowiadanie różnych historii',1,132);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (526,'grę na instrumencie',0,132);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (527,'obgotowywanie mięsa',0,132);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (528,'uprawianie ogrodu',0,132);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (529,'szlafrok',1,133);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (530,'szafka przy łóżku',0,133);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (531,'kołysanka',0,133);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (532,'świeczka',0,133);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (533,'ocean',1,134);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (534,'podróżnik',0,134);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (535,'globus',0,134);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (536,'snop siana',0,134);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (537,'człowieka spokojnego',1,135);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (538,'księgowego',0,135);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (539,'matematyka',0,135);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (540,'przedsiębiorcę',0,135);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (541,'ogrodzenie',1,136);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (542,'smród',0,136);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (543,'rysia',0,136);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (544,'randkę',0,136);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (545,'woreczek do przechowywania pieniędzy',1,137);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (546,'narzędzie do młócenia zboża',0,137);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (547,'czerpak do nabierania wody',0,137);
INSERT INTO `answer` (`id`,`answer_content`,`correct`,`question_id`) VALUES (548,'sznury do wywieszania prania',0,137);
